---

# Contains a list of units. Every unit contains logic (similar to a LUT in a
# CPLD).
# Units contain AND gates and OR gates. The order of AND and OR gates is
# controled by 'and_then_or' flag. Every input can be inverted.
# If the inputs need to be stable and logical '1' for a specific amount of time
# specify 'input_stable_usec'. If the input is not stable or logical '0' the
# result is '0'.
# If the first gate is AND and 'invert_first_gate' is set, it acts like a NAND
# gate.
# If the first gate is OR and 'invert_first_gate' is set, it acts like a NOR
# gate.
# Specify 'delay_usec' to delay the output signal by usec.

inputs:
  # FIVR_FAULT is not read as THERMTRIP_N is driven as well.
  - name: "H_LVT3_CPLD0_THERMTRIP_N"
    signal_name: "H_LVT3_CPLD0_THERMTRIP"
    type: "gpio"
    active_low: true
    description: >
      THERMTRIP_N is set on over tempertature condition or internal FIVR fault.

  - name: "FM_CPU0_SKTOCC_N"
    signal_name: "FM_CPU0_SKTOCC"
    type: "gpio"
    active_low: true
    description: "CPU0 is socketed."

  - name: "PWRGD_PVTT_ABC_CPU0"
    signal_name: "PWRGD_PVTT_ABC_CPU0"
    type: "gpio"
    active_low: true

  - name: "PWRGD_PVTT_DEF_CPU0"
    signal_name: "PWRGD_PVTT_DEF_CPU0"
    type: "gpio"
    active_low: true

outputs:
  - name: "FM_CPU0_ADR_COMPLETE_DLY"
    type: "gpio"
    signal_name: "FM_CPU0_ADR_COMPLETE_DLY"
    description: "ADR complete delayed."

  - name: "H_LVT3_CPU0_PROCHOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU0_PROCHOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU0 is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU0_MEM_ABC_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU0_MEM_ABC_HOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU0 memory is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU0_MEM_DEF_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU0_MEM_DEF_HOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU0 memory is hot and throttling. Open Drain."

  - name: "PWRGD_LVC3_CPU0_ABC_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU0_ABC_DRAM_G"
    description: "CPU0 DRAM power good signal."

  - name: "PWRGD_LVC3_CPU0_DEF_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU0_DEF_DRAM_G"
    description: "CPU0 DRAM power good signal."

  - name: "PWRGD_LVC3_CPU0_PWRGOOD"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU0_PWRGOOD"
    description: "CPU0 power good signal."

  - name: "RST_LVC3_CPU0_RESET_N"
    type: "gpio"
    signal_name: "RST_LVC3_CPU0_RESET_N"
    description: "CPU0 RESET_N"

immutables:
  - signal_name: "FM_CPU0_ADR_COMPLETE_DLY"
    value: false

power_sequencer:
  # DDR_PVPP must ramp before DDR_VDDQ, must retain 30 msec after DDR_VDDQ goes
  # low
  # CPU0 DDR VR
  - PVPP_ABC_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_ABC_DELAY"
          - name: "PVDDQ_ABC_Enabled"
        and:
         - name: "FM_CPU0_SKTOCC"
      out:
        name: "PVPP_ABC_On"

  # Ramp after DDR_VPP
  - PVDDQ_ABC_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_ABC_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU0_SKTOCC"
      out:
        name: "PVDDQ_ABC_On"

  - PVDDQ_ABC_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_ABC_Enabled"
      out:
        name: "PVDDQ_ABC_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PVPP_DEF_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_DEF_DELAY"
          - name: "PVDDQ_DEF_Enabled"
        and:
          - name: "FM_CPU0_SKTOCC"
      out:
        name: "PVPP_DEF_On"

  # Ramp after DDR_VPP
  - PVDDQ_DEF_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_DEF_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU0_SKTOCC"
      out:
        name: "PVDDQ_DEF_On"
  - PVDDQ_DEF_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_DEF_Enabled"
      out:
        name: "PVDDQ_DEF_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PWRGD_LVC3_CPU0_ABC_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_ABC_PowerGood"
          - name: "PVPP_ABC_PowerGood"
          - name: "PWRGD_PVTT_ABC_CPU0"
      out:
        name: "PWRGD_LVC3_CPU0_ABC_DRAM_G"

  - PWRGD_LVC3_CPU0_DEF_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_DEF_PowerGood"
          - name: "PVPP_DEF_PowerGood"
          - name: "PWRGD_PVTT_DEF_CPU0"
      out:
        name: "PWRGD_LVC3_CPU0_DEF_DRAM_G"

  - CPU0_DDR_PWRGD_Unit:
      in:
        and:
          - name: "PWRGD_LVC3_CPU0_ABC_DRAM_G"
          - name: "PWRGD_LVC3_CPU0_DEF_DRAM_G"
        or:
          - name: "FM_CPU0_SKTOCC"
            invert: true
      out:
        name: "CPU0_DDR_PWRGD"
      and_then_or: true

  - PWRGD_LVC3_CPU0_PWRGOOD_Unit:
      in:
        and:
          - name: "CPU0_DDR_PWRGD"
          - name: "CPU0_VR_PWRGD" # fast path
          - name: "PWRGD_CPUPWRGD" # signal from PCH (slow)
          - name: "FM_CPU0_SKTOCC"
      out:
        name: "PWRGD_LVC3_CPU0_PWRGOOD"

  - CPU0_DDR_Off_Unit:
      in:
        and:
          - name: "PVDDQ_ABC_Enabled"
            invert: true
          - name: "PVPP_ABC_Enabled"
            invert: true
          - name: "PVDDQ_DEF_Enabled"
            invert: true
          - name: "PVPP_DEF_Enabled"
            invert: true
      out:
        name: "CPU0_DDR_Off"
  
  - CPU0_VR_Off_Unit:
      in:
        and:
          - name: "PVCCIO_CPU0_Enabled"
            invert: true
          - name: "PVCCIN_CPU0_Enabled"
            invert: true
          - name: "PVCCSA_CPU0_Enabled"
            invert: true
      out:
        name: "CPU0_VR_Off"
  
  - CPU0_VR_Off_Unit:
    in:
      and:
        - name: "CPU0_DDR_Off"
        - name: "CPU0_VR_Off"
    out:
      name: "CPU0_Off"
    
  - CPU0_VR_Fault_Unit:
      in:
        or:
          - name: "PVDDQ_ABC_Fault"
          - name: "PVPP_ABC_Fault"
          - name: "PVDDQ_DEF_Fault"
          - name: "PVPP_DEF_Fault"
          - name: "PVCCIO_CPU0_Fault"
          - name: "PVCCIN_CPU0_Fault"
          - name: "PVCCSA_CPU0_Fault"
        and:
          - name: "FM_CPU0_SKTOCC"
            invert: true
      out:
        name: "CPU0_VR_Fault"

  - CPU0_VR_Fault_Keep_Unit:
      in:
        or:
          - name: "CPU0_VR_Fault"
          - name: "CPU0_VR_Fault_Shutdown"
        and:
          - name: "CPU0_Off"
            invert: true
      out:
        name: "CPU0_VR_Fault_Shutdown"

  # PVCCIO must ramp before PVCCIN and PVCCSA, must retain until after PVCCIN
  # and PVCCSA goes low
  # A fault on PVCCIO must shutdown PVCCIN and PVCCSA
  - PVCCIO_CPU0_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU0_DDR_PWRGD"
            input_stable_usec: 100
          - name: "FM_CPU0_SKTOCC"
        or:
          - name: "PVCCIO_CPU0_DELAY"
      out:
        name: "PVCCIO_CPU0_On"
      and_then_or: true

  - PVCCIO_CPU0_Delay_Unit:
      in:
        or:
          - name: "PVCCIN_CPU0_On"
          - name: "PVCCSA_CPU0_On"
      out:
        name: "PVCCIO_CPU0_DELAY"
      delay_usec: 5000

  - PVCCIN_CPU0_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "PVCCIO_CPU0_PowerGood"
            input_stable_usec: 100
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCIN_CPU0_On"
      delay_usec: 10 # Must retain for at least 10usec after shutdown

  - PVCCSA_CPU0_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "PVCCIN_CPU0_PowerGood"
            input_stable_usec: 100
          - name: "PVCCIO_CPU0_PowerGood"
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCSA_CPU0_On"
      delay_usec: 10 # Must retain for at least 10usec after shutdown

  - CPU0_VR_PWRGD_Unit:
      in:
        and:
          - name: "PVCCIO_CPU0_PowerGood"
          - name: "PVCCIN_CPU0_PowerGood"
            input_stable_usec: 1800  # CPUPWRGD must assert 1.8msec after PVCCIN
          - name: "PVCCSA_CPU0_PowerGood"
        or:
          - name: "FM_CPU0_SKTOCC"
            invert: true
      out:
        name: "CPU0_VR_PWRGD"
      and_then_or: true

  - CPU0_THERMTRIP_Unit:
      in:
        and:
          - name: "H_LVT3_CPLD0_THERMTRIP"
          - name: "CPU0_VR_PWRGD"
            input_stable_usec: 1500
      out:
        name: "CPU0_THERMTRIP"

  - H_LVT3_CPU0_PROCHOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU0_SKTOCC"
      out:
        name: "H_LVT3_CPU0_PROCHOT"

  - H_LVT3_CPU0_MEM_ABC_HOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU0_SKTOCC"
      out:
        name: "H_LVT3_CPU0_MEM_ABC_HOT"

  - H_LVT3_CPU0_MEM_DEF_HOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU0_SKTOCC"
      out:
        name: "H_LVT3_CPU0_MEM_DEF_HOT"