---

# List of PMBUS controlled voltage regulators
# Every voltage regulator emits a <name>_Enabled and <name>_Fault output signal
# Every voltage regulator emits a <name>_On input signal
# Volage regulators are configured on program start, and only read
# on fault conditions.
# A fault triggers an interrupt and starts the internal state machine.
regulators:
  - name: "PVPP_ABC"
  - name: "PVDDQ_ABC"
  - name: "PVPP_DEF"
  - name: "PVDDQ_DEF"
  - name: "PVPP_GHJ"
  - name: "PVDDQ_GHJ"
  - name: "PVPP_KLM"
  - name: "PVDDQ_KLM"
  - name: "PVPP_NPQ"
  - name: "PVDDQ_NPQ"
  - name: "PVPP_RST"
  - name: "PVDDQ_RST"
  - name: "PVPP_UVW"
  - name: "PVDDQ_UVW"
  - name: "PVPP_XYZ"
  - name: "PVDDQ_XYZ"
  - name: "PVCCIO_CPU0"
  - name: "PVCCIO_CPU1"
  - name: "PVCCIO_CPU2"
  - name: "PVCCIO_CPU3"
  - name: "PVCCIN_CPU0"
  - name: "PVCCIN_CPU1"
  - name: "PVCCIN_CPU2"
  - name: "PVCCIN_CPU3"
  - name: "PVCCSA_CPU0"
  - name: "PVCCSA_CPU1"
  - name: "PVCCSA_CPU2"
  - name: "PVCCSA_CPU3"

