---

# Contains a list of units. Every unit contains logic (similar to a LUT in a
# CPLD).
# Units contain AND gates and OR gates. The order of AND and OR gates is
# controled by 'and_then_or' flag. Every input can be inverted.
# If the inputs need to be stable and logical '1' for a specific amount of time
# specify 'input_stable_usec'. If the input is not stable or logical '0' the
# result is '0'.
# If the first gate is AND and 'invert_first_gate' is set, it acts like a NAND
# gate.
# If the first gate is OR and 'invert_first_gate' is set, it acts like a NOR
# gate.
# Specify 'delay_usec' to delay the output signal by usec.

power_sequencer:
  # DDR_PVPP must ramp before DDR_VDDQ, must retain 30 msec after DDR_VDDQ goes
  # low
  # CPU0 DDR VR
  - PVPP_ABC_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_ABC_DELAY"
          - name: "PVDDQ_ABC_Enabled"
        and:
         - name: "FM_CPU0_SKTOCC_N"
      out:
        name: "PVPP_ABC_On"

  # Ramp after DDR_VPP
  - PVDDQ_ABC_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_ABC_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU0_SKTOCC_N"
      out:
        name: "PVDDQ_ABC_On"

  - PVDDQ_ABC_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_ABC_Enabled"
      out:
        name: "PVDDQ_ABC_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PVPP_DEF_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_DEF_DELAY"
          - name: "PVDDQ_DEF_Enabled"
        and:
          - name: "FM_CPU0_SKTOCC_N"
      out:
        name: "PVPP_DEF_On"

  # Ramp after DDR_VPP
  - PVDDQ_DEF_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_DEF_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU0_SKTOCC_N"
      out:
        name: "PVDDQ_DEF_On"

  - PVDDQ_DEF_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_DEF_Enabled"
      out:
        name: "PVDDQ_DEF_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PWRGD_LVC3_CPU0_ABC_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_ABC_PowerGood"
          - name: "PVPP_ABC_PowerGood"
          - name: "PWRGD_PVTT_ABC_CPU0"
      out:
        name: "PWRGD_LVC3_CPU0_ABC_DRAM_G"

  - PWRGD_LVC3_CPU0_DEF_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_DEF_PowerGood"
          - name: "PVPP_DEF_PowerGood"
          - name: "PWRGD_PVTT_DEF_CPU0"
      out:
        name: "PWRGD_LVC3_CPU0_DEF_DRAM_G"

  - CPU0_DDR_PWRGD_Unit:
      in:
        and:
          - name: "PWRGD_LVC3_CPU0_ABC_DRAM_G"
          - name: "PWRGD_LVC3_CPU0_DEF_DRAM_G"
        or:
          - name: "FM_CPU0_SKTOCC_N"
      out:
        name: "CPU0_DDR_PWRGD"
      and_then_or: true

  - PWRGD_LVC3_CPU0_PWRGOOD_Unit:
      in:
        and:
          - name: "PWRGD_CPUPWRGD"
          - name: "FM_CPU0_SKTOCC_N"
            invert: true
      out:
        name: "PWRGD_LVC3_CPU0_PWRGOOD"

  # PVCCIO must ramp before PVCCIN and PVCCSA, must retain until after PVCCIN
  # and PVCCSA goes low
  # A fault on PVCCIO must shutdown PVCCIN and PVCCSA
  - PVCCIO_CPU0_Unit:
      in:
        and:
          - name: "CPU0_DDR_PWRGD"
            input_stable_usec: 100
          - name: "FM_CPU0_SKTOCC_N"
            invert: true
        or:
          - name: "PVCCIO_CPU0_DELAY"
      out:
        name: "PVCCIO_CPU0_On"
      and_then_or: true

  - PVCCIO_CPU0_Delay_Unit:
      in:
        or:
          - name: "PVCCIN_CPU0_On"
          - name: "PVCCSA_CPU0_On"
      out:
        name: "PVCCIO_CPU0_DELAY"
      delay_usec: 5000

  - PVCCIN_CPU0_Unit:
      in:
        and:
          - name: "PVCCIO_CPU0_PowerGood"
            input_stable_usec: 100
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCIN_CPU0_On"

  - PVCCSA_CPU0_Unit:
      in:
        and:
          - name: "PVCCIN_CPU0_PowerGood"
            input_stable_usec: 100
          - name: "PVCCIO_CPU0_PowerGood"
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCSA_CPU0_On"

  - CPU0_VR_PWRGD_Unit:
      in:
        and:
          - name: "PVCCIO_CPU0_PowerGood"
          - name: "PVCCIN_CPU0_PowerGood"
            input_stable_usec: 1800  # CPUPWRGD must assert 1.8msec after PVCCIN
          - name: "PVCCSA_CPU0_PowerGood"
        or:
          - name: "FM_CPU0_SKTOCC_N"
      out:
        name: "CPU0_VR_PWRGD"
      and_then_or: true
