---

# Contains a list of units. Every unit contains logic (similar to a LUT in a
# CPLD).
# Units contain AND gates and OR gates. The order of AND and OR gates is
# controled by 'and_then_or' flag. Every input can be inverted.
# If the inputs need to be stable and logical '1' for a specific amount of time
# specify 'input_stable_usec'. If the input is not stable or logical '0' the
# result is '0'.
# If the first gate is AND and 'invert_first_gate' is set, it acts like a NAND
# gate.
# If the first gate is OR and 'invert_first_gate' is set, it acts like a NOR
# gate.
# Specify 'delay_usec' to delay the output signal by usec.

inputs:
  - name: "H_LVT3_CPLD1_THERMTRIP_N"
    signal_name: "H_LVT3_CPLD1_THERMTRIP"
    type: "gpio"
    active_low: true
    description: >
      THERMTRIP_N is set on over tempertature condition or internal FIVR fault.

  - name: "FM_CPU1_SKTOCC_N"
    signal_name: "FM_CPU1_SKTOCC"
    type: "gpio"
    active_low: true
    description: "CPU1 is socketed."

  - name: "PWRGD_PVTT_GHJ_CPU1"
    signal_name: "PWRGD_PVTT_GHJ_CPU1"
    type: "gpio"
    active_low: true

  - name: "PWRGD_PVTT_KLM_CPU1"
    signal_name: "PWRGD_PVTT_KLM_CPU1"
    type: "gpio"
    active_low: true

outputs:
  - name: "FM_CPU1_ADR_COMPLETE_DLY"
    type: "gpio"
    signal_name: "FM_CPU1_ADR_COMPLETE_DLY"
    description: "ADR complete delayed."

  - name: "H_LVT3_CPU1_PROCHOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU1_PROCHOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU1 is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU1_MEM_GHJ_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU1_MEM_GHJ_HOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU1 memory is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU1_MEM_KLM_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU1_MEM_KLM_HOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU1 memory is hot and throttling. Open Drain."

  - name: "PWRGD_LVC3_CPU1_GHJ_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU1_GHJ_DRAM_G"
    description: "CPU1 DRAM power good signal."

  - name: "PWRGD_LVC3_CPU1_KLM_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU1_KLM_DRAM_G"
    description: "CPU1 DRAM power good signal."

  - name: "PWRGD_LVC3_CPU1_PWRGOOD"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU1_PWRGOOD"
    description: "CPU1 power good signal."

  - name: "RST_LVC3_CPU1_RESET_N"
    type: "gpio"
    signal_name: "RST_LVC3_CPU1_RESET_N"
    description: "CPU1 RESET_N"
    
immutables:
  - signal_name: "FM_CPU1_ADR_COMPLETE_DLY"
    value: false

power_sequencer:
 
  # CPU1 DDR VR
  - PVPP_GHJ_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_GHJ_DELAY"
          - name: "PVDDQ_GHJ_Enabled"
        and:
          - name: "FM_CPU1_SKTOCC"
      out:
        name: "PVPP_GHJ_On"

  # Ramp after DDR_VPP
  - PVDDQ_GHJ_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_GHJ_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU1_SKTOCC"
      out:
        name: "PVDDQ_GHJ_On"

  - PVDDQ_GHJ_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_GHJ_Enabled"
      out:
        name: "PVDDQ_GHJ_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PVPP_KLM_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_KLM_DELAY"
          - name: "PVDDQ_KLM_Enabled"
        and:
          - name: "FM_CPU1_SKTOCC"
      out:
        name: "PVPP_KLM_On"

  # Ramp after DDR_VPP
  - PVDDQ_KLM_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_KLM_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU1_SKTOCC"
      out:
        name: "PVDDQ_KLM_On"

  - PVDDQ_KLM_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_KLM_Enabled"
      out:
        name: "PVDDQ_KLM_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PWRGD_LVC3_CPU1_GHJ_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_GHJ_PowerGood"
          - name: "PVPP_GHJ_PowerGood"
          - name: "PWRGD_PVTT_GHJ_CPU0"
      out:
        name: "PWRGD_LVC3_CPU1_GHJ_DRAM_G"

  - PWRGD_LVC3_CPU1_KLM_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_KLM_PowerGood"
          - name: "PVPP_KLM_PowerGood"
          - name: "PWRGD_PVTT_KLM_CPU0"
      out:
        name: "PWRGD_LVC3_CPU1_KLM_DRAM_G"

  - CPU1_DDR_PWRGD_Unit:
      in:
        and:
          - name: "PWRGD_LVC3_CPU1_GHJ_DRAM_G"
          - name: "PWRGD_LVC3_CPU1_KLM_DRAM_G"
        or:
          - name: "FM_CPU1_SKTOCC"
            invert: true
      out:
        name: "CPU1_DDR_PWRGD"
    and_then_or: true

  - PWRGD_LVC3_CPU1_PWRGOOD_Unit:
      in:
        and:
          - name: "CPU1_DDR_PWRGD"
          - name: "CPU1_VR_PWRGD" # fast path
          - name: "PWRGD_CPUPWRGD" # signal from PCH (slow)
          - name: "FM_CPU1_SKTOCC"
      out:
        name: "PWRGD_LVC3_CPU1_PWRGOOD"

  # PVCCIO must ramp before PVCCIN and PVCCSA, must retain until after PVCCIN
  # and PVCCSA goes low
  # A fault on PVCCIO must shutdown PVCCIN and PVCCSA
  - PVCCIO_CPU1_Unit:
      in:
        and:
          - name: "CPU0_DDR_PWRGD"
            input_stable_usec: 100
          - name: "FM_CPU1_SKTOCC"
        or:
          - name: "PVCCIO_CPU1_DELAY"
      out:
        name: "PVCCIO_CPU1_On"
      and_then_or: true

  - PVCCIO_CPU1_Delay_Unit:
      in:
        or:
          - name: "PVCCIN_CPU1_On"
          - name: "PVCCSA_CPU1_On"
      out:
        name: "PVCCIO_CPU1_DELAY"
      delay_usec: 5000

  - PVCCIN_CPU1_Unit:
      in:
        and:
          - name: "PVCCIO_CPU1_PowerGood"
            input_stable_usec: 100
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCIN_CPU1_On"
      delay_usec: 10 # Must retain for at least 10usec after shutdown

  - PVCCSA_CPU1_Unit:
      in:
        and:
          - name: "PVCCIN_CPU1_PowerGood"
            input_stable_usec: 100
          - name: "PVCCIO_CPU1_PowerGood"
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCSA_CPU1_On"
      delay_usec: 10 # Must retain for at least 10usec after shutdown

  - CPU1_VR_PWRGD_Unit:
      in:
        and:
          - name: "PVCCIO_CPU1_PowerGood"
          - name: "PVCCIN_CPU1_PowerGood"
            input_stable_usec: 1800  # CPUPWRGD must assert 1.8msec after PVCCIN
          - name: "PVCCSA_CPU1_PowerGood"
        or:
          - name: "FM_CPU1_SKTOCC"
            invert: true
      out:
        name: "CPU1_VR_PWRGD"
      and_then_or: true

  - CPU1_THERMTRIP_Unit:
      in:
        and:
          - name: "H_LVT3_CPLD1_THERMTRIP"
          - name: "CPU1_VR_PWRGD"
            input_stable_usec: 1500
      out:
        name: "CPU1_THERMTRIP"

  - FM_CPU_CATERR_CPU1_Enable_Unit:
      in:
        and:
          - name: "CPU1_VR_PWRGD"
            input_stable_usec: 1500
          - name: "FM_BIOS_POST_CMPLT"
          - name: "FM_CPU1_SKTOCC"
      out:
        name: "CATERR_CPU1_EN"

  - H_LVT3_CPU1_PROCHOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU1_SKTOCC"
      out:
        name: "H_LVT3_CPU1_PROCHOT"

  - H_LVT3_CPU1_MEM_GHJ_HOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU1_SKTOCC"
      out:
        name: "H_LVT3_CPU1_MEM_GHJ_HOT"

  - H_LVT3_CPU1_MEM_KLM_HOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU1_SKTOCC"
      out:
        name: "H_LVT3_CPU1_MEM_KLM_HOT"
