---

# Contains a list of units. Every unit contains logic (similar to a LUT in a
# CPLD).
# Units contain AND gates and OR gates. The order of AND and OR gates is
# controled by 'and_then_or' flag. Every input can be inverted.
# If the inputs need to be stable and logical '1' for a specific amount of time
# specify 'input_stable_usec'. If the input is not stable or logical '0' the
# result is '0'.
# If the first gate is AND and 'invert_first_gate' is set, it acts like a NAND
# gate.
# If the first gate is OR and 'invert_first_gate' is set, it acts like a NOR
# gate.
# Specify 'delay_usec' to delay the output signal by usec.

power_sequencer:
 
  # CPU1 DDR VR
  - PVPP_GHJ_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_GHJ_DELAY"
          - name: "PVDDQ_GHJ_Enabled"
        and:
          - name: "FM_CPU1_SKTOCC_N"
      out:
        name: "PVPP_GHJ_On"

  # Ramp after DDR_VPP
  - PVDDQ_GHJ_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_GHJ_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU1_SKTOCC_N"
      out:
        name: "PVDDQ_GHJ_On"

  - PVDDQ_GHJ_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_GHJ_Enabled"
      out:
        name: "PVDDQ_GHJ_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PVPP_KLM_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_KLM_DELAY"
          - name: "PVDDQ_KLM_Enabled"
        and:
          - name: "FM_CPU1_SKTOCC_N"
      out:
        name: "PVPP_KLM_On"

  # Ramp after DDR_VPP
  - PVDDQ_KLM_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_KLM_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU1_SKTOCC_N"
      out:
        name: "PVDDQ_KLM_On"

  - PVDDQ_KLM_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_KLM_Enabled"
      out:
        name: "PVDDQ_KLM_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PWRGD_LVC3_CPU1_GHJ_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_GHJ_PowerGood"
          - name: "PVPP_GHJ_PowerGood"
          - name: "PWRGD_PVTT_GHJ_CPU0"
      out:
        name: "PWRGD_LVC3_CPU1_GHJ_DRAM_G"

  - PWRGD_LVC3_CPU1_KLM_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_KLM_PowerGood"
          - name: "PVPP_KLM_PowerGood"
          - name: "PWRGD_PVTT_KLM_CPU0"
      out:
        name: "PWRGD_LVC3_CPU1_KLM_DRAM_G"

  - CPU1_DDR_PWRGD_Unit:
      in:
        and:
          - name: "PWRGD_LVC3_CPU1_GHJ_DRAM_G"
          - name: "PWRGD_LVC3_CPU1_KLM_DRAM_G"
        or:
          - name: "FM_CPU1_SKTOCC_N"
      out:
        name: "CPU1_DDR_PWRGD"
    and_then_or: true

  - PWRGD_LVC3_CPU1_PWRGOOD_Unit:
      in:
        and:
          - name: "PWRGD_CPUPWRGD"
          - name: "FM_CPU1_SKTOCC_N"
            invert: true
      out:
        name: "PWRGD_LVC3_CPU1_PWRGOOD"

  # PVCCIO must ramp before PVCCIN and PVCCSA, must retain until after PVCCIN
  # and PVCCSA goes low
  # A fault on PVCCIO must shutdown PVCCIN and PVCCSA
  - PVCCIO_CPU1_Unit:
      in:
        and:
          - name: "CPU0_DDR_PWRGD"
            input_stable_usec: 100
          - name: "FM_CPU1_SKTOCC_N"
            invert: true
        or:
          - name: "PVCCIO_CPU1_DELAY"
      out:
        name: "PVCCIO_CPU1_On"
      and_then_or: true

  - PVCCIO_CPU1_Delay_Unit:
      in:
        or:
          - name: "PVCCIN_CPU1_On"
          - name: "PVCCSA_CPU1_On"
      out:
        name: "PVCCIO_CPU1_DELAY"
      delay_usec: 5000

  - PVCCIN_CPU1_Unit:
      in:
        and:
          - name: "PVCCIO_CPU1_PowerGood"
            input_stable_usec: 100
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCIN_CPU1_On"

  - PVCCSA_CPU1_Unit:
      in:
        and:
          - name: "PVCCIN_CPU1_PowerGood"
            input_stable_usec: 100
          - name: "PVCCIO_CPU1_PowerGood"
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCSA_CPU1_On"

  - CPU1_VR_PWRGD_Unit:
      in:
        and:
          - name: "PVCCIO_CPU1_PowerGood"
          - name: "PVCCIN_CPU1_PowerGood"
            input_stable_usec: 1800  # CPUPWRGD must assert 1.8msec after PVCCIN
          - name: "PVCCSA_CPU1_PowerGood"
        or:
          - name: "FM_CPU1_SKTOCC_N"
      out:
        name: "CPU1_VR_PWRGD"
      and_then_or: true
