---

# Contains a list of units. Every unit contains logic (similar to a LUT in a
# CPLD).
# Units contain AND gates and OR gates. The order of AND and OR gates is
# controled by 'and_then_or' flag. Every input can be inverted.
# If the inputs need to be stable and logical '1' for a specific amount of time
# specify 'input_stable_usec'. If the input is not stable or logical '0' the
# result is '0'.
# If the first gate is AND and 'invert_first_gate' is set, it acts like a NAND
# gate.
# If the first gate is OR and 'invert_first_gate' is set, it acts like a NOR
# gate.
# Specify 'delay_usec' to delay the output signal by usec.

inputs:
  - name: "H_LVT3_CPLD2_THERMTRIP_N"
    signal_name: "H_LVT3_CPLD2_THERMTRIP"
    type: "gpio"
    active_low: true
    description: >
      THERMTRIP_N is set on over tempertature condition or internal FIVR fault.

  - name: "FM_CPU2_SKTOCC_N"
    signal_name: "FM_CPU2_SKTOCC"
    type: "gpio"
    active_low: true
    description: "CPU2 is socketed."

  - name: "PWRGD_PVTT_NPQ_CPU2"
    signal_name: "PWRGD_PVTT_NPQ_CPU2"
    type: "gpio"
    active_low: true

  - name: "PWRGD_PVTT_RST_CPU2"
    signal_name: "PWRGD_PVTT_RST_CPU2"
    type: "gpio"
    active_low: true

outputs:
  - name: "FM_CPU2_ADR_COMPLETE_DLY"
    type: "gpio"
    signal_name: "FM_CPU2_ADR_COMPLETE_DLY"
    description: "ADR complete delayed."

  - name: "H_LVT3_CPU2_PROCHOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU2_PROCHOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU2 is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU2_MEM_NPQ_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU2_MEM_NPQ_HOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU2 memory is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU2_MEM_RST_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU2_MEM_RST_HOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU2 memory is hot and throttling. Open Drain."

  - name: "PWRGD_LVC3_CPU2_NPQ_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU2_NPQ_DRAM_G"
    description: "CPU2 DRAM power good signal."
  
  - name: "PWRGD_LVC3_CPU2_RST_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU2_RST_DRAM_G"
    description: "CPU2 DRAM power good signal."

  - name: "PWRGD_LVC3_CPU2_PWRGOOD"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU2_PWRGOOD"
    description: "CPU2 power good signal."

  - name: "RST_LVC3_CPU2_RESET_N"
    type: "gpio"
    signal_name: "RST_LVC3_CPU2_RESET_N"
    description: "CPU2 RESET_N"

constants:
  - signal_name: "FM_CPU2_ADR_COMPLETE_DLY"
    value: false

power_sequencer:
  
  # CPU2 DDR VR
  - PVPP_NPQ_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_NPQ_DELAY"
          - name: "PVDDQ_NPQ_Enabled"
        and:
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "PVPP_NPQ_On"

  # Ramp after DDR_VPP
  - PVDDQ_NPQ_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_NPQ_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "PVDDQ_NPQ_On"

  - PVDDQ_NPQ_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_NPQ_Enabled"
      out:
        name: "PVDDQ_NPQ_DELAY"
    delay_usec: 30000  # JEDEC recommendation

  - PVPP_RST_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_RST_DELAY"
          - name: "PVDDQ_RST_Enabled"
        and:
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "PVPP_RST_On"

  # Ramp after DDR_VPP
  - PVDDQ_RST_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_RST_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "PVDDQ_RST_On"

  - PVDDQ_RST_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_RST_Enabled"
      out:
        name: "PVDDQ_RST_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PWRGD_LVC3_CPU2_NPQ_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_NPQ_PowerGood"
          - name: "PVPP_NPQ_PowerGood"
          - name: "PWRGD_PVTT_NPQ_CPU0"
      out:
        name: "PWRGD_LVC3_CPU2_NPQ_DRAM_G"

  - PWRGD_LVC3_CPU2_RST_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_RST_PowerGood"
          - name: "PVPP_RST_PowerGood"
          - name: "PWRGD_PVTT_RST_CPU0"
      out:
        name: "PWRGD_LVC3_CPU2_RST_DRAM_G"

  - CPU2_DDR_PWRGD_Unit:
      in:
        and:
          - name: "PWRGD_LVC3_CPU2_NPQ_DRAM_G"
          - name: "PWRGD_LVC3_CPU2_RST_DRAM_G"
        or:
          - name: "FM_CPU2_SKTOCC"
            invert: true
      out:
        name: "CPU2_DDR_PWRGD"
      and_then_or: true

  - PWRGD_LVC3_CPU2_PWRGOOD_Unit:
      in:
        and:
          - name: "PWRGD_CPUPWRGD"
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "PWRGD_LVC3_CPU2_PWRGOOD"

  - PVCCIO_CPU2_Unit:
      in:
        and:
          - name: "CPU2_DDR_PWRGD"
            input_stable_usec: 100
          - name: "FM_CPU2_SKTOCC"
        or:
          - name: "PVCCIO_CPU2_DELAY"
      out:
        name: "PVCCIO_CPU2_On"
      and_then_or: true

  - PVCCIO_CPU2_Delay_Unit:
      in:
        or:
          - name: "PVCCIN_CPU2_On"
          - name: "PVCCSA_CPU2_On"
      out:
        name: "PVCCIO_CPU2_DELAY"
    delay_usec: 5000

  - PVCCIN_CPU2_Unit:
      in:
        and:
          - name: "PVCCIO_CPU2_PowerGood"
            input_stable_usec: 100
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCIN_CPU2_On"

  - PVCCSA_CPU2_Unit:
      in:
        and:
          - name: "PVCCIN_CPU2_PowerGood"
            input_stable_usec: 100
          - name: "PVCCIO_CPU2_PowerGood"
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCSA_CPU2_On"

  - CPU2_VR_PWRGD_Unit:
      in:
        and:
          - name: "PVCCIO_CPU2_PowerGood"
          - name: "PVCCIN_CPU2_PowerGood"
            input_stable_usec: 1800  # CPUPWRGD must assert 1.8msec after PVCCIN
          - name: "PVCCSA_CPU2_PowerGood"
        or:
          - name: "FM_CPU2_SKTOCC"
            invert: true
      out:
        name: "CPU2_VR_PWRGD"
      and_then_or: true

  - CPU2_THERMTRIP_Unit:
      in:
        and:
          - name: "H_LVT3_CPLD2_THERMTRIP"
          - name: "CPU2_VR_PWRGD"
              input_stable_usec: 1500
      out:
        name: "CPU2_THERMTRIP"

  - FM_CPU_CATERR_CPU2_Enable_Unit:
      in:
        and:
          - name: "CPU2_VR_PWRGD"
              input_stable_usec: 1500
          - name: "FM_BIOS_POST_CMPLT"
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "CATERR_CPU2_EN"

  - H_LVT3_CPU2_PROCHOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "H_LVT3_CPU2_PROCHOT"

  - H_LVT3_CPU2_MEM_NPQ_HOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "H_LVT3_CPU2_MEM_NPQ_HOT"

  - H_LVT3_CPU2_MEM_RST_HOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "H_LVT3_CPU2_MEM_RST_HOT"