---

# Contains a list of units. Every unit contains logic (similar to a LUT in a
# CPLD).
# Units contain AND gates and OR gates. The order of AND and OR gates is
# controled by 'and_then_or' flag. Every input can be inverted.
# If the inputs need to be stable and logical '1' for a specific amount of time
# specify 'input_stable_usec'. If the input is not stable or logical '0' the
# result is '0'.
# If the first gate is AND and 'invert_first_gate' is set, it acts like a NAND
# gate.
# If the first gate is OR and 'invert_first_gate' is set, it acts like a NOR
# gate.
# Specify 'delay_usec' to delay the output signal by usec.

inputs:
  - name: "H_LVT3_CPLD3_THERMTRIP_N"
    signal_name: "H_LVT3_CPLD3_THERMTRIP"
    type: "gpio"
    active_low: true
    description: >
      THERMTRIP_N is set on over tempertature condition or internal FIVR fault.

  - name: "FM_CPU3_SKTOCC_N"
    signal_name: "FM_CPU3_SKTOCC_N"
    type: "gpio"
    active_low: true
    description: "CPU3 is socketed."

  - name: "PWRGD_PVTT_UVW_CPU3"
    signal_name: "PWRGD_PVTT_UVW_CPU3"
    type: "gpio"
    active_low: true
  
  - name: "PWRGD_PVTT_XYZ_CPU3"
    signal_name: "PWRGD_PVTT_XYZ_CPU3"
    type: "gpio"
    active_low: true

power_sequencer:
  # CPU3 DDR VR
  - PVPP_UVW_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_UVW_DELAY"
          - name: "PVDDQ_UVW_Enabled"
        and:
          - name: "FM_CPU3_SKTOCC_N"
      out:
        name: "PVPP_UVW_On"

  # Ramp after DDR_VPP
  - PVDDQ_UVW_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_UVW_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU3_SKTOCC_N"
      out:
        name: "PVDDQ_UVW_On"

  - PVDDQ_UVW_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_UVW_Enabled"
      out:
        name: "PVDDQ_UVW_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PVPP_XYZ_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_XYZ_DELAY"
          - name: "PVDDQ_XYZ_Enabled"
        and:
          - name: "FM_CPU3_SKTOCC_N"
      out:
        name: "PVPP_XYZ_On"

  # Ramp after DDR_VPP
  - PVDDQ_XYZ_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_XYZ_Enabled"
            input_stable_usec: 100
          - name: "FM_CPU3_SKTOCC_N"
      out:
        name: "PVDDQ_XYZ_On"

  - PVDDQ_XYZ_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_XYZ_Enabled"
      out:
        name: "PVDDQ_XYZ_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PWRGD_LVC3_CPU3_UVW_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_UVW_PowerGood"
          - name: "PVPP_UVW_PowerGood"
          - name: "PWRGD_PVTT_UVW_CPU3"
      out:
        name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"

  - PWRGD_LVC3_CPU3_XYZ_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_XYZ_PowerGood"
          - name: "PVPP_XYZ_PowerGood"
          - name: "PWRGD_PVTT_XYZ_CPU3"
      out:
        name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"

  - CPU3_DDR_PWRGD_Unit:
      in:
        and:
          - name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"
          - name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"
        or:
          - name: "FM_CPU3_SKTOCC_N"
      out:
        name: "CPU3_DDR_PWRGD"
      and_then_or: true

  - PWRGD_LVC3_CPU3_PWRGOOD_Unit:
      in:
        and:
          - name: "PWRGD_CPUPWRGD"
          - name: "FM_CPU3_SKTOCC_N"
            invert: true
      out:
        name: "PWRGD_LVC3_CPU3_PWRGOOD"

  - PVCCIO_CPU3_Unit:
      in:
        and:
          - name: "CPU3_DDR_PWRGD"
            input_stable_usec: 100
          - name: "FM_CPU3_SKTOCC_N"
            invert: true
        or:
          - name: "PVCCIO_CPU3_DELAY"
      out:
        name: "PVCCIO_CPU3_On"
      and_then_or: true

  - PVCCIO_CPU3_Delay_Unit:
      in:
        or:
          - name: "PVCCIN_CPU3_On"
          - name: "PVCCSA_CPU3_On"
      out:
        name: "PVCCIO_CPU3_DELAY"
      delay_usec: 5000

  - PVCCIN_CPU3_Unit:
      in:
        and:
          - name: "PVCCIO_CPU3_PowerGood"
            input_stable_usec: 100
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCIN_CPU3_On"

  - PVCCSA_CPU3_Unit:
      in:
        and:
          - name: "PVCCIN_CPU3_PowerGood"
            input_stable_usec: 100
          - name: "PVCCIO_CPU3_PowerGood"
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCSA_CPU3_On"

  - CPU3_VR_PWRGD_Unit:
      in:
        and:
          - name: "PVCCIO_CPU3_PowerGood"
          - name: "PVCCIN_CPU3_PowerGood"
            input_stable_usec: 1800  # CPUPWRGD must assert 1.8msec after PVCCIN
          - name: "PVCCSA_CPU3_PowerGood"
        or:
          - name: "FM_CPU3_SKTOCC_N"
      out:
        name: "CPU3_VR_PWRGD"
      and_then_or: true

  - CPU3_THERMTRIP_Unit:
      in:
        and:
          - name: "H_LVT3_CPLD3_THERMTRIP"
          - name: "CPU3_VR_PWRGD"
            input_stable_usec: 1500
      out:
        name: "CPU3_THERMTRIP"

  - FM_CPU_CATERR_CPU3_Enable_Unit:
      in:
        and:
          - name: "CATERR_CPU3_EN"
          - name: "FM_BIOS_POST_CMPLT"
          - name: "FM_CPU3_SKTOCC_N"
            invert: true
      out:
        name: "CATERR_CPU3_EN"