---

# Contains a list of units. Every unit contains logic (similar to a LUT in a
# CPLD).
# Units contain AND gates and OR gates. The order of AND and OR gates is
# controled by 'and_then_or' flag. Every input can be inverted.
# If the inputs need to be stable and logical '1' for a specific amount of time
# specify 'input_stable_usec'. If the input is not stable or logical '0' the
# result is '0'.
# If the first gate is AND and 'invert_first_gate' is set, it acts like a NAND
# gate.
# If the first gate is OR and 'invert_first_gate' is set, it acts like a NOR
# gate.
# Specify 'delay_usec' to delay the output signal by usec.

power_sequencer:

  # DRAM is powered in S3 and S0
  - DDR_Power_Unit:
      in:
        and:
          - name: "FM_SLPS4_N"
      out:
        name: "DDR_POWER"

  - CPU_DDR_PWRGD_Unit:
      in:
        and:
          - name: "CPU0_DDR_PWRGD"
          - name: "CPU1_DDR_PWRGD"
          - name: "CPU2_DDR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
      out:
        name: "CPU_DDR_PWRGD"

  - CPU_VR_PWRGD_Unit:
      in:
        and:
          - name: "CPU0_VR_PWRGD"
          - name: "CPU1_VR_PWRGD"
          - name: "CPU2_VR_PWRGD"
          - name: "CPU3_VR_PWRGD"
      out:
        name: "CPU_VR_PWRGD"

  # TODO: Add 100 msec delay here if rails power PCIe devices reset along
  # with PLTRST_N
  - PWRGD_PCH_PWROK_Unit:
      in:
        and:
          - name: "CPU_DDR_PWRGD"
          - name: "CPU_VR_PWRGD"
      out:
        name: "PWRGD_PCH_PWROK"


