---

# Contains a list of units. Every unit contains logic (similar to a LUT in a
# CPLD).
# Units contain AND gates and OR gates. The order of AND and OR gates is
# controled by 'and_then_or' flag. Every input can be inverted.
# If the inputs need to be stable and logical '1' for a specific amount of time
# specify 'input_stable_usec'. If the input is not stable or logical '0' the
# result is '0'.
# If the first gate is AND and 'invert_first_gate' is set, it acts like a NAND
# gate.
# If the first gate is OR and 'invert_first_gate' is set, it acts like a NOR
# gate.
# Specify 'delay_usec' to delay the output signal by usec.

power_sequencer:

  # P5V0 is not an input of PCH.
  # There are no USB ports.
  # P5V0 is to provide bias voltage to CPU VRs.
  - P5V0_Unit:
      in:
        and:
          - name: "P5V_AUX_PowerGood"
          - name: "FM_SLPS4_N"
            invert: true
      out:
        name: "AUX_SSB_5V0_On"

  # DRAM is powered in S3 and S0
  - DDR_Power_Unit:
      in:
        and:
          - name: "FM_SLPS4_N"
      out:
        name: "DDR_POWER"

  - CPU_POWER_Unit:
      in:
        and:
          - name: "FM_SLPS3"
            invert: true
      out:
        name: "CPU_POWER"

  - CPU_DDR_PWRGD_Unit:
      in:
        and:
          - name: "CPU0_DDR_PWRGD"
          - name: "CPU1_DDR_PWRGD"
          - name: "CPU2_DDR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
      out:
        name: "CPU_DDR_PWRGD"

  - CPU_VR_PWRGD_Unit:
      in:
        and:
          - name: "CPU0_VR_PWRGD"
          - name: "CPU1_VR_PWRGD"
          - name: "CPU2_VR_PWRGD"
          - name: "CPU3_VR_PWRGD"
      out:
        name: "CPU_VR_PWRGD"

  # The following violates multi-processor RESET_N spec
  - RST_LVC3_CPU0_RESET_N_Unit:
      in:
        and:
          - name: "PLTRST_N"
      out:
        name: "RST_LVC3_CPU0_RESET_N"

  - RST_LVC3_CPU1_RESET_N_Unit:
      in:
        and:
          - name: "PLTRST_N"
      out:
        name: "RST_LVC3_CPU1_RESET_N"

  - RST_LVC3_CPU2_RESET_N_Unit:
      in:
        and:
          - name: "PLTRST_N"
      out:
        name: "RST_LVC3_CPU2_RESET_N"

  - RST_LVC3_CPU3_RESET_N_Unit:
      in:
        and:
          - name: "PLTRST_N"
      out:
        name: "RST_LVC3_CPU3_RESET_N"

  - RST_PCIE_PCH_PERST_N_Unit:
      in:
        and:
          - name: "PLTRST_N"
      out:
        name: "RST_PCIE_PCH_PERST_N"

  - CPU_THERMTRIP_Unit:
      in:
        or:
          - name: "CPU0_THERMTRIP"
          - name: "CPU1_THERMTRIP"
          - name: "CPU2_THERMTRIP"
          - name: "CPU3_THERMTRIP"
      out:
        name: "THRMTRIP_N"

  - FM_CPU_CATERR_LVT3_Unit:
      in:
        and:
          - name: "FM_CPU_CATERR_LVT3"
          - name: "CPU_VR_PWRGD"
      out:
        name: "H_LVT3_CATERR_DLY"
      delay_us: 500 # Spec

  - FM_ADR_TRIGGER_R_Unit:
      in:
        and:
          - name: "FM_ADR_TRIGGER_R"
          - name: "PLTRST_N"
          - name: "PWRGD_CPUPWRGD"
        or:
          - name: "FM_ADR_TRIGGER_R_Internal"
        and_then_or: true
      out:
        name: "FM_ADR_TRIGGER_R"


immutables:
  # No power good from main PSU. ADR flow not supported.
  - FM_ADR_TRIGGER_R:
    signal_name: "FM_ADR_TRIGGER_R_Internal"
    value: false
