---
# List of outputs controlled by the program. An output can be a GPIO or
# a voltage regulator
outputs:
  - H_LVT1_THERMTRIP_N:
    name: "THRMTRIP_N"
    type: "gpio"
    active_low: true
    description: >
      Signal from CPU indicating an overheat condition. PCH will got to S5
      without following normal transition flow.
    comment: >
      PCH will immediately drive CPUPWRGD low and assert PLTRST_N, SLP_S3_N,
      SLP_S4_N, SLP_S5_N.
  - PWRGD_SYS_PWROK:
    type: "gpio"
    name: "SYS_PWROK"
    description: "Generic power good. CPU is good to come out of reset."
    comment: "!SLP_S3, PCH_PWROK, CPU rails enabled && CPU rails OK"
  - PWRGD_PCH_PWROK:
    type: "gpio"
    name: "PCH_PWROK"
    description: "PCH core power good for at least 10msec."
    comment: "!FM_SLPS3_N && PCH_PWR_EN && !FAULT"
  - PWRGD_PCH_DPWROK:
    type: "gpio"
    name: "DSW_PWROK"
    description: >
      PCH core power good for at least 10msec. Min 1 usec after RTCRST_N
  - RST_PCH_RSMRST_R_N:
    type: "gpio"
    name: "RSMRST_N"
    description: >
      All PCH primary power rails are stable for 10 msec.
      Either assert after SLP_SUS_N or 100msec after DSW_PWROK assertion.
  - PWRGD_LVC3_CPU0_ABC_DRAM_G:
    type: "gpio"
    name: "PWRGD_LVC3_CPU0_ABC_DRAM_G"
    description: "CPU0 DRAM power good signal."
  - PWRGD_LVC3_CPU0_DEF_DRAM_G:
    type: "gpio"
    name: "PWRGD_LVC3_CPU0_DEF_DRAM_G"
    description: "CPU0 DRAM power good signal."
  - PWRGD_LVC3_CPU1_GHJ_DRAM_G:
    type: "gpio"
    name: "PWRGD_LVC3_CPU1_GHJ_DRAM_G"
    description: "CPU1 DRAM power good signal."
  - PWRGD_LVC3_CPU1_KLM_DRAM_G:
    type: "gpio"
    name: "PWRGD_LVC3_CPU1_KLM_DRAM_G"
    description: "CPU1 DRAM power good signal."
  - PWRGD_LVC3_CPU2_NPQ_DRAM_G:
    type: "gpio"
    name: "PWRGD_LVC3_CPU2_NPQ_DRAM_G"
    description: "CPU2 DRAM power good signal."
  - PWRGD_LVC3_CPU2_RST_DRAM_G:
    type: "gpio"
    name: "PWRGD_LVC3_CPU2_RST_DRAM_G"
    description: "CPU2 DRAM power good signal."
  - PWRGD_LVC3_CPU3_UVW_DRAM_G:
    type: "gpio"
    name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"
    description: "CPU3 DRAM power good signal."
  - PWRGD_LVC3_CPU3_XYZ_DRAM_G:
    type: "gpio"
    name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"
    description: "CPU3 DRAM power good signal."
  - PWRGD_LVC3_CPU0_PWRGOOD:
    type: "gpio"
    name: "PWRGD_LVC3_CPU0_PWRGOOD"
    description: "CPU0 power good signal."
  - PWRGD_LVC3_CPU1_PWRGOOD:
    type: "gpio"
    name: "PWRGD_LVC3_CPU1_PWRGOOD"
    description: "CPU1 power good signal."
  - PWRGD_LVC3_CPU2_PWRGOOD:
    type: "gpio"
    name: "PWRGD_LVC3_CPU2_PWRGOOD"
    description: "CPU2 power good signal."
  - PWRGD_LVC3_CPU3_PWRGOOD:
    type: "gpio"
    name: "PWRGD_LVC3_CPU3_PWRGOOD"
    description: "CPU3 power good signal."

