---
# List of outputs controlled by the program. An output can be a GPIO or
# a voltage regulator
outputs:
  - name: "H_LVT1_THERMTRIP_N"
    signal_name: "THRMTRIP_N"
    type: "gpio"
    active_low: true
    description: >
      Signal from BMC to PCH indicating an overheat condition. PCH will got to S5
      without following normal transition flow.
    comment: >
      PCH will immediately drive CPUPWRGD low and assert PLTRST_N, SLP_S3_N,
      SLP_S4_N, SLP_S5_N.
  
  - name: "H_LVT3_CATERR_DLY_N"
    signal_name: "H_LVT3_CATERR_DLY"
    type: "gpio"
    active_low: true
    description: "Delayed CATERR signal from any CPU. "
    # FIXME: Maximum pulse width from CPU is 160nsec.

  - name: "CATERR_CPU1_EN"
    signal_name: "CATERR_CPU1_EN"
    type: "gpio"
    description: "Enable CPU1 CATERR"

  - name: "CATERR_CPU2_EN"
    signal_name: "CATERR_CPU2_EN"
    type: "gpio"
    description: "Enable CPU2 CATERR"

  - name: "CATERR_CPU3_EN"
    signal_name: "CATERR_CPU3_EN"
    type: "gpio"
    description: "Enable CPU3 CATERR"

  - name: "PWRGD_SYS_PWROK"
    type: "gpio"
    signal_name: "SYS_PWROK"
    description: "Generic power good. CPU is good to come out of reset."
    comment: "!SLP_S3, PCH_PWROK, CPU rails enabled && CPU rails OK"

  - name: "PWRGD_PCH_PWROK"
    type: "gpio"
    signal_name: "PCH_PWROK"
    description: "PCH core power good for at least 10msec."
    comment: "!FM_SLPS3_N && PCH_PWR_EN && !FAULT"
  - name: "PWRGD_PCH_DPWROK"
    type: "gpio"
    signal_name: "DSW_PWROK"
    description: >
      PCH core power good for at least 10msec. Min 1 usec after RTCRST_N
  - name: "RST_PCH_RSMRST_R_N"
    type: "gpio"
    signal_name: "RSMRST_N"
    description: >
      All PCH primary power rails are stable for 10 msec.
      Either assert after SLP_SUS_N or 100msec after DSW_PWROK assertion.
  - name: "PWRGD_LVC3_CPU0_ABC_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU0_ABC_DRAM_G"
    description: "CPU0 DRAM power good signal."
  - name: "PWRGD_LVC3_CPU0_DEF_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU0_DEF_DRAM_G"
    description: "CPU0 DRAM power good signal."
  - name: "PWRGD_LVC3_CPU1_GHJ_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU1_GHJ_DRAM_G"
    description: "CPU1 DRAM power good signal."
  - name: "PWRGD_LVC3_CPU1_KLM_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU1_KLM_DRAM_G"
    description: "CPU1 DRAM power good signal."
  - name: "PWRGD_LVC3_CPU2_NPQ_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU2_NPQ_DRAM_G"
    description: "CPU2 DRAM power good signal."
  - name: "PWRGD_LVC3_CPU2_RST_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU2_RST_DRAM_G"
    description: "CPU2 DRAM power good signal."
  - name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"
    description: "CPU3 DRAM power good signal."
  - name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"
    description: "CPU3 DRAM power good signal."
  - name: "PWRGD_LVC3_CPU0_PWRGOOD"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU0_PWRGOOD"
    description: "CPU0 power good signal."
  - name: "PWRGD_LVC3_CPU1_PWRGOOD"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU1_PWRGOOD"
    description: "CPU1 power good signal."
  - name: "PWRGD_LVC3_CPU2_PWRGOOD"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU2_PWRGOOD"
    description: "CPU2 power good signal."
  - name: "PWRGD_LVC3_CPU3_PWRGOOD"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU3_PWRGOOD"
    description: "CPU3 RESET_N"
  - name: "RST_LVC3_CPU2_RESET_N"
    type: "gpio"
    signal_name: "RST_LVC3_CPU2_RESET_N"
    description: "CPU2 RESET_N"
  - name: "RST_LVC3_CPU1_RESET_N"
    type: "gpio"
    signal_name: "RST_LVC3_CPU1_RESET_N"
    description: "CPU1 RESET_N"
  - name: "RST_LVC3_CPU0_RESET_N"
    type: "gpio"
    signal_name: "RST_LVC3_CPU0_RESET_N"
    description: "CPU0 RESET_N"
  - name: "RST_PCIE_PCH_PERST_N"
    type: "gpio"
    signal_name: "RST_PCIE_PCH_PERST_N"
    description: "PCH PCIe reset signal"

  - name: "FM_ADR_TRIGGER_R_N"
    type: "gpio"
    active_low: true
    signal_name: "FM_ADR_TRIGGER_R"
    description: "Trigger ADR flow."