---

# Contains a list of units. Every unit contains logic (similar to a LUT in a
# CPLD).
# Units contain AND gates and OR gates. The order of AND and OR gates is
# controled by 'and_then_or' flag. Every input can be inverted.
# If the inputs need to be stable and logical '1' for a specific amount of time
# specify 'input_stable_usec'. If the input is not stable or logical '0' the
# result is '0'.
# If the first gate is AND and 'invert_first_gate' is set, it acts like a NAND
# gate.
# If the first gate is OR and 'invert_first_gate' is set, it acts like a NOR
# gate.
# Specify 'delay_usec' to delay the output signal by usec.

inputs:
  - name: "H_LVT3_CPLD3_THERMTRIP_N"
    signal_name: "H_LVT3_CPLD3_THERMTRIP"
    type: "gpio"
    active_low: true
    description: >
      THERMTRIP_N is set on over tempertature condition or internal FIVR fault.

  - name: "FM_CPU3_SKTOCC_N"
    signal_name: "FM_CPU3_SKTOCC"
    type: "gpio"
    active_low: true
    description: "CPU3 is socketed."

  - name: "PWRGD_PVTT_UVW_CPU3"
    signal_name: "PWRGD_PVTT_UVW_CPU3"
    type: "gpio"
    active_low: true
  
  - name: "PWRGD_PVTT_XYZ_CPU3"
    signal_name: "PWRGD_PVTT_XYZ_CPU3"
    type: "gpio"
    active_low: true

outputs:
  - name: "FM_CPU3_ADR_COMPLETE_DLY"
    type: "gpio"
    signal_name: "FM_CPU3_ADR_COMPLETE_DLY"
    description: "ADR complete delayed."

  - name: "H_LVT3_CPU3_PROCHOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU3_PROCHOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU3 is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU3_MEM_UVW_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU3_MEM_UVW_HOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU3 memory is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU3_MEM_XYZ_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU3_MEM_XYZ_HOT"
    active_low: true
    #FIXME: gpio_mode: "OD" with weak pull up
    description: "CPU3 memory is hot and throttling. Open Drain."

  - name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"
    description: "CPU3 DRAM power good signal."

  - name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"
    description: "CPU3 DRAM power good signal."

  - name: "PWRGD_LVC3_CPU3_PWRGOOD"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU3_PWRGOOD"
    description: "CPU3 RESET_N"

  - name: "RST_LVC3_CPU3_RESET_N"
    type: "gpio"
    signal_name: "RST_LVC3_CPU3_RESET_N"
    description: "CPU3 RESET_N"

immutables:
  - signal_name: "FM_CPU3_ADR_COMPLETE_DLY"
    value: false

power_sequencer:
  # Vpp must be equal or higher than Vdd at all times.
  - PVPP_UVW_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_UVW_DELAY"
          - name: "PVDDQ_UVW_Enabled"
        and:
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "PVPP_UVW_On"

  # Ramp after DDR_VPP
  - PVDDQ_UVW_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_UVW_PowerGood"
            input_stable_usec: 100
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "PVDDQ_UVW_On"

  - PVDDQ_UVW_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_UVW_Enabled"
      out:
        name: "PVDDQ_UVW_DELAY"
      delay_usec: 30000  # JEDEC recommendation
  
  # Vpp must be equal or higher than Vdd at all times.
  - PVPP_XYZ_Unit:
      in:
        or:
          - name: "DDR_POWER"
          - name: "PVDDQ_XYZ_DELAY"
          - name: "PVDDQ_XYZ_Enabled"
        and:
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "PVPP_XYZ_On"

  # Ramp after DDR_VPP
  - PVDDQ_XYZ_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "PVPP_XYZ_PowerGood"
            input_stable_usec: 100
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "PVDDQ_XYZ_On"

  - PVDDQ_XYZ_Delay_Unit:
      in:
        and:
          - name: "PVDDQ_XYZ_Enabled"
      out:
        name: "PVDDQ_XYZ_DELAY"
      delay_usec: 30000  # JEDEC recommendation

  - PWRGD_LVC3_CPU3_UVW_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_UVW_PowerGood"
          - name: "PVPP_UVW_PowerGood"
          - name: "PWRGD_PVTT_UVW_CPU3"
      out:
        name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"

  - PWRGD_LVC3_CPU3_XYZ_DRAM_G_Unit:
      in:
        and:
          - name: "PVDDQ_XYZ_PowerGood"
          - name: "PVPP_XYZ_PowerGood"
          - name: "PWRGD_PVTT_XYZ_CPU3"
      out:
        name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"

  - CPU3_DDR_PWRGD_Unit:
      in:
        and:
          - name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"
          - name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"
        or:
          - name: "FM_CPU3_SKTOCC"
            invert: true
      out:
        name: "CPU3_DDR_PWRGD"
      and_then_or: true

  - PWRGD_LVC3_CPU3_PWRGOOD_Unit:
      in:
        and:
          - name: "CPU3_DDR_PWRGD"
          - name: "CPU3_VR_PWRGD" # fast path
          - name: "PWRGD_CPUPWRGD" # signal from PCH (slow)
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "PWRGD_LVC3_CPU3_PWRGOOD"

  - CPU3_DDR_Off_Unit:
      in:
        and:
          - name: "PVDDQ_UVW_Enabled"
            invert: true
          - name: "PVPP_UVW_Enabled"
            invert: true
          - name: "PVDDQ_XYZ_Enabled"
            invert: true
          - name: "PVPP_XYZ_Enabled"
            invert: true
      out:
        name: "CPU3_DDR_Off"
  
  - CPU3_VR_Off_Unit:
      in:
        and:
          - name: "PVCCIO_CPU3_Enabled"
            invert: true
          - name: "PVCCIN_CPU3_Enabled"
            invert: true
          - name: "PVCCSA_CPU3_Enabled"
            invert: true
      out:
        name: "CPU3_VR_Off"
  
  - CPU3_VR_Off_Unit:
    in:
      and:
        - name: "CPU3_DDR_Off"
        - name: "CPU3_VR_Off"
    out:
      name: "CPU3_Off"
    
  - CPU3_VR_Fault_Unit:
      in:
        or:
          - name: "PVDDQ_UVW_Fault"
          - name: "PVPP_UVW_Fault"
          - name: "PVDDQ_XYZ_Fault"
          - name: "PVPP_XYZ_Fault"
          - name: "PVCCIO_CPU3_Fault"
          - name: "PVCCIN_CPU3_Fault"
          - name: "PVCCSA_CPU3_Fault"
        and:
          - name: "FM_CPU3_SKTOCC"
            invert: true
      out:
        name: "CPU3_VR_Fault"

  - CPU3_VR_Fault_Keep_Unit:
      in:
        or:
          - name: "CPU3_VR_Fault"
          - name: "CPU3_VR_Fault_Shutdown"
        and:
          - name: "CPU3_Off"
            invert: true
      out:
        name: "CPU3_VR_Fault_Shutdown"
    
  - PVCCIO_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU3_DDR_PWRGD"
            input_stable_usec: 100
          - name: "FM_CPU3_SKTOCC"
        or:
          - name: "PVCCIO_CPU3_DELAY"
      out:
        name: "PVCCIO_CPU3_On"
      and_then_or: true

  - PVCCIO_CPU3_Delay_Unit:
      in:
        or:
          - name: "PVCCIN_CPU3_On"
          - name: "PVCCSA_CPU3_On"
      out:
        name: "PVCCIO_CPU3_DELAY"
      delay_usec: 5000

  - PVCCIN_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "PVCCIO_CPU3_PowerGood"
            input_stable_usec: 100
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCIN_CPU3_On"
      delay_usec: 10 # Must retain for at least 10usec after shutdown

  - PVCCSA_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "PVCCIN_CPU3_PowerGood"
            input_stable_usec: 100
          - name: "PVCCIO_CPU3_PowerGood"
          - name: "AUX_SSB_5V0_PowerGood"
      out:
        name: "PVCCSA_CPU3_On"
      delay_usec: 10 # Must retain for at least 10usec after shutdown

  - CPU3_VR_PWRGD_Unit:
      in:
        and:
          - name: "PVCCIO_CPU3_PowerGood"
          - name: "PVCCIN_CPU3_PowerGood"
            input_stable_usec: 1800  # CPUPWRGD must assert 1.8msec after PVCCIN
          - name: "PVCCSA_CPU3_PowerGood"
        or:
          - name: "FM_CPU3_SKTOCC"
            invert: true
      out:
        name: "CPU3_VR_PWRGD"
      and_then_or: true

  - CPU3_THERMTRIP_Unit:
      in:
        and:
          - name: "H_LVT3_CPLD3_THERMTRIP"
          - name: "CPU3_VR_PWRGD"
            input_stable_usec: 1500
      out:
        name: "CPU3_THERMTRIP"

  - FM_CPU_CATERR_CPU3_Enable_Unit:
      in:
        and:
          - name: "CPU3_VR_PWRGD"
            input_stable_usec: 1500
          - name: "FM_BIOS_POST_CMPLT"
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "CATERR_CPU3_EN"

  - H_LVT3_CPU3_PROCHOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "H_LVT3_CPU3_PROCHOT"

  - H_LVT3_CPU3_MEM_UVW_HOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "H_LVT3_CPU3_MEM_UVW_HOT"

  - H_LVT3_CPU3_MEM_XYZ_HOT_Unit:
      in:
        and:
          - name: "FM_THROTTLE"
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "H_LVT3_CPU3_MEM_XYZ_HOT"
