---
# Inputs are monitored using interrupts and trigger the internal state machine.
inputs:

  - name: "PWRGD_CPUPWRGD"
    type: "gpio"
    signal_name: "PWRGD_CPUPWRGD"
    description: "PROC_PWRGD. PCH informs the CPU that power is stable and clocks are running."

  - name: "RST_PLTRST_N"
    signal_name: "PLTRST_N"
    type: "gpio"
    description: >
      Global platform reset signal.
      Not all PCIe devices might be affected by this signal.
  
  - name: "FM_CPU_CATERR_LVT3_N"
    signal_name: "FM_CPU_CATERR_LVT3"
    type: "gpio"
    active_low: true
    description: >
      Catastrophic error from CPU.
  
  - name: "FM_BIOS_POST_CMPLT_N"
    signal_name: "FM_BIOS_POST_CMPLT"
    type: "gpio"
    active_low: true
    description: >
      Signal from BIOS that post is complete.

  # MSMI_N not handled. No input at PCH?
  # ERROR_N not handled. Not related to power sequencing.

  - name: "FM_THROTTLE_N"
    signal_name: "FM_THROTTLE"
    type: "gpio"
    active_low: true
    description: >
      Signal from BIOS that something is getting hot. Throttle CPU and memory.