---
# List of outputs controlled by the program. An output can be a GPIO or
# a voltage regulator
outputs:
  - name: "H_LVT1_THERMTRIP_N"
    signal_name: "THRMTRIP"
    type: "gpio"
    active_low: true
    description: >
      Signal from BMC to PCH indicating an overheat condition. PCH will got to S5
      without following normal transition flow.
    comment: >
      PCH will immediately drive CPUPWRGD low and assert PLTRST_N, SLP_S3_N,
      SLP_S4_N, SLP_S5_N.
  
  - name: "H_LVT3_CATERR_DLY_N"
    signal_name: "H_LVT3_CATERR_DLY"
    type: "gpio"
    active_low: true
    description: "Delayed CATERR signal from any CPU. "
    # FIXME: Maximum pulse width from CPU is 160nsec.

  - name: "CATERR_CPU1_EN"
    signal_name: "CATERR_CPU1_EN"
    type: "gpio"
    description: "Enable CPU1 CATERR"

  - name: "CATERR_CPU2_EN"
    signal_name: "CATERR_CPU2_EN"
    type: "gpio"
    description: "Enable CPU2 CATERR"

  - name: "CATERR_CPU3_EN"
    signal_name: "CATERR_CPU3_EN"
    type: "gpio"
    description: "Enable CPU3 CATERR"

  - name: "PWRGD_SYS_PWROK"
    type: "gpio"
    signal_name: "SYS_PWROK"
    description: "Generic power good. CPU is good to come out of reset."
    comment: "!SLP_S3, PCH_PWROK, CPU rails enabled && CPU rails OK"

  - name: "RST_PCIE_PCH_PERST_N"
    type: "gpio"
    signal_name: "RST_PCIE_PCH_PERST_N"
    description: "PCH PCIe reset signal"

  - name: "FM_ADR_TRIGGER_R_N"
    type: "gpio"
    active_low: true
    signal_name: "FM_ADR_TRIGGER_R"
    description: "Trigger ADR flow."